name: CD
on:
 push:
   branches: [master]
jobs:
  ghp:
    name: cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium --only-shell

      - name: Run unit tests
        run: npm test

      - name: Run e2e tests
        env:
          CI: true
        run: npm run test:e2e

      - name: Build for GitHub Pages
        run: npm run buildGH

      - name: Deploy to gh-pages
        shell: bash
        env:
          GITUSER: ${{ secrets.GITUSER }}
          EMAIL: ${{ secrets.EMAIL }}
        run: sh .devops/deploy.sh "$GITUSER" "$EMAIL"
